fail_fast: true

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: debug-statements
        id: trailing-whitespace
        id: end-of-file-fixer
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.2'
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
